### ISSUE TITLE
Peer -to-peer Review

### ISSUE THREAD

**Issue by Nedramrez** [Strangeal/Portfolio#5]
Hi!
Nice job so far!
Please check the Figma design of your project.

https://github.com/Strangeal/Portfolio/blob/018772540722df3c9d6b8182c9f50edfe8390065/header.css#L76-L78

Please check the` padding-top `property of the `"dev-child" <div> `so your headline section would be as it is at Figma design.

https://github.com/Strangeal/Portfolio/blob/018772540722df3c9d6b8182c9f50edfe8390065/header.css#L277-L294

Please add the `padding` protperty to "form-child" <div> and try to make it closer to the Figma design.

**Comment by Strangeal** [comment]
Thanks for the review.
